import NavigationSidebar from "@/components/dashboard/dashboard-sidebar";
import "../globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { NextAuthProvider } from "@/components/providers";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "OpenInApp",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <NextAuthProvider>
          <div className="h-full bg-[#f8faff]">
            <div className="hidden md:flex h-full w-[280px] z-30 fixed inset-y-0">
              <NavigationSidebar />
            </div>
            <main className="h-full md:pl-[280px]">{children}</main>
          </div>
        </NextAuthProvider>
      </body>
    </html>
  );
}
